# Message-based natural language control of the kuka for a simple teaching task.

allegro_hand_control:
  # List of topics
  topics:
    - KUKA/TokenControl : String
  KUKA/TokenControl:
    okay robot stop: STOP_DEMONSTRATION
    okay robot start task: unused
    okay robot teach task: START_DEMONSTRATION
    stop: STOP_DEMONSTRATION
